version: "4"
services:
  mufin-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - /usr/src/app/**/**/node_modules # local 의 node_modules 을 참조
      - ./:/user/src/app # local 의 코드를 참조
#  redis:
#    image: "redis"
  db:
    image: "postgres"

#    volumes:
#      - .:/code
#    depends_on:
#      - db
#  db:
#    image: postgres
#    volumes:
#      - db-data:/var/lib/postgresql/data