version: "3.8"
services:
  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - nestjs
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/logs:/var/log/nginx
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    shm_size: 128mb
    build:
      context: ./libs/database
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    env_file:
#      - .env
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    volumes:
      - /usr/src/app/node_modules # local 의 node_modules 을 참조
      - ./:/usr/src/app # local 의 코드를 참조
    container_name: nestjs
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
